# Generated by Django 3.0.6 on 2020-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('name', models.TextField(max_length=40)),
                ('city', models.TextField(max_length=40)),
            ],
        ),
    ]
