# Generated by Django 3.0.6 on 2020-06-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.TextField(max_length=40)),
                ('lastname', models.TextField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemList',
        ),
    ]
